In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Carregar os dados
df_dados = pd.read_csv('df_2017_2.csv', sep=',')  # substitua pelo caminho do seu arquivo


# Filtrar as classes com mais de uma instância
class_counts = df_dados['status'].value_counts()
classes_to_keep = class_counts[class_counts > 1].index
df_filtered = df_dados[df_dados['status'].isin(classes_to_keep)]

# Separar as variáveis independentes e dependentes
x = df_filtered.drop(columns=['status']).to_numpy()
y = df_filtered['status'].to_numpy()

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

# Treinar o classificador SVM
classifier = SVC(kernel='linear', C=1)
classifier.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = classifier.predict(X_test)

# Avaliar a precisão do classificador
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do classificador SVM:", accuracy)

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de confusão:")
print(conf_matrix)

# Exibir o relatório de classificação
class_report = classification_report(y_test, y_pred)
print("Relatório de classificação:")
print(class_report)

Acurácia do classificador SVM: 0.875
Matriz de confusão:
[[9 1]
 [1 5]]
Relatório de classificação:
              precision    recall  f1-score   support

          -1       0.90      0.90      0.90        10
           1       0.83      0.83      0.83         6

    accuracy                           0.88        16
   macro avg       0.87      0.87      0.87        16
weighted avg       0.88      0.88      0.88        16



In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Carregar os dados
df_dados = pd.read_csv('df_2018_1.csv', sep=',')  # substitua pelo caminho do seu arquivo


# Filtrar as classes com mais de uma instância
class_counts = df_dados['status'].value_counts()
classes_to_keep = class_counts[class_counts > 1].index
df_filtered = df_dados[df_dados['status'].isin(classes_to_keep)]

# Separar as variáveis independentes e dependentes
x = df_filtered.drop(columns=['status']).to_numpy()
y = df_filtered['status'].to_numpy()

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

# Treinar o classificador SVM
classifier = SVC(kernel='linear', C=1)
classifier.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = classifier.predict(X_test)

# Avaliar a precisão do classificador
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do classificador SVM:", accuracy)

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de confusão:")
print(conf_matrix)

# Exibir o relatório de classificação
class_report = classification_report(y_test, y_pred)
print("Relatório de classificação:")
print(class_report)

Acurácia do classificador SVM: 0.7857142857142857
Matriz de confusão:
[[5 2]
 [1 6]]
Relatório de classificação:
              precision    recall  f1-score   support

          -1       0.83      0.71      0.77         7
           1       0.75      0.86      0.80         7

    accuracy                           0.79        14
   macro avg       0.79      0.79      0.78        14
weighted avg       0.79      0.79      0.78        14



In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Carregar os dados
df_dados = pd.read_csv('df_2019_4.csv', sep=',')  # substitua pelo caminho do seu arquivo


# Filtrar as classes com mais de uma instância
class_counts = df_dados['status'].value_counts()
classes_to_keep = class_counts[class_counts > 1].index
df_filtered = df_dados[df_dados['status'].isin(classes_to_keep)]

# Separar as variáveis independentes e dependentes
x = df_filtered.drop(columns=['status']).to_numpy()
y = df_filtered['status'].to_numpy()

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

# Treinar o classificador SVM
classifier = SVC(kernel='linear', C=1)
classifier.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = classifier.predict(X_test)

# Avaliar a precisão do classificador
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do classificador SVM:", accuracy)

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de confusão:")
print(conf_matrix)

# Exibir o relatório de classificação
class_report = classification_report(y_test, y_pred)
print("Relatório de classificação:")
print(class_report)

Acurácia do classificador SVM: 0.8666666666666667
Matriz de confusão:
[[6 2]
 [0 7]]
Relatório de classificação:
              precision    recall  f1-score   support

          -1       1.00      0.75      0.86         8
           1       0.78      1.00      0.88         7

    accuracy                           0.87        15
   macro avg       0.89      0.88      0.87        15
weighted avg       0.90      0.87      0.87        15



In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Carregar os dados
df_dados = pd.read_csv('df_2019_4.csv', sep=',')  # substitua pelo caminho do seu arquivo


# Filtrar as classes com mais de uma instância
class_counts = df_dados['status'].value_counts()
classes_to_keep = class_counts[class_counts > 1].index
df_filtered = df_dados[df_dados['status'].isin(classes_to_keep)]

# Separar as variáveis independentes e dependentes
x = df_filtered.drop(columns=['status']).to_numpy()
y = df_filtered['status'].to_numpy()

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

# Treinar o classificador SVM
classifier = SVC(kernel='linear', C=1)
classifier.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = classifier.predict(X_test)

# Avaliar a precisão do classificador
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do classificador SVM:", accuracy)

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de confusão:")
print(conf_matrix)

# Exibir o relatório de classificação
class_report = classification_report(y_test, y_pred)
print("Relatório de classificação:")
print(class_report)

Acurácia do classificador SVM: 0.8666666666666667
Matriz de confusão:
[[6 2]
 [0 7]]
Relatório de classificação:
              precision    recall  f1-score   support

          -1       1.00      0.75      0.86         8
           1       0.78      1.00      0.88         7

    accuracy                           0.87        15
   macro avg       0.89      0.88      0.87        15
weighted avg       0.90      0.87      0.87        15



In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Carregar os dados
df_dados = pd.read_csv('df_2019_6.csv', sep=',')  # substitua pelo caminho do seu arquivo


# Filtrar as classes com mais de uma instância
class_counts = df_dados['status'].value_counts()
classes_to_keep = class_counts[class_counts > 1].index
df_filtered = df_dados[df_dados['status'].isin(classes_to_keep)]

# Separar as variáveis independentes e dependentes
x = df_filtered.drop(columns=['status']).to_numpy()
y = df_filtered['status'].to_numpy()

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

# Treinar o classificador SVM
classifier = SVC(kernel='linear', C=1)
classifier.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = classifier.predict(X_test)

# Avaliar a precisão do classificador
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do classificador SVM:", accuracy)

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de confusão:")
print(conf_matrix)

# Exibir o relatório de classificação
class_report = classification_report(y_test, y_pred)
print("Relatório de classificação:")
print(class_report)

Acurácia do classificador SVM: 0.8666666666666667
Matriz de confusão:
[[6 2]
 [0 7]]
Relatório de classificação:
              precision    recall  f1-score   support

          -1       1.00      0.75      0.86         8
           1       0.78      1.00      0.88         7

    accuracy                           0.87        15
   macro avg       0.89      0.88      0.87        15
weighted avg       0.90      0.87      0.87        15



In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Carregar os dados
df_dados = pd.read_csv('df_bsi_sem_ativo.csv', sep=',')  # substitua pelo caminho do seu arquivo


# Filtrar as classes com mais de uma instância
class_counts = df_dados['status'].value_counts()
classes_to_keep = class_counts[class_counts > 1].index
df_filtered = df_dados[df_dados['status'].isin(classes_to_keep)]

# Separar as variáveis independentes e dependentes
x = df_filtered.drop(columns=['status']).to_numpy()
y = df_filtered['status'].to_numpy()

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

# Treinar o classificador SVM
classifier = SVC(kernel='linear', C=1)
classifier.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = classifier.predict(X_test)

# Avaliar a precisão do classificador
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do classificador SVM:", accuracy)

# Exibir a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de confusão:")
print(conf_matrix)

# Exibir o relatório de classificação
class_report = classification_report(y_test, y_pred)
print("Relatório de classificação:")
print(class_report)

Acurácia do classificador SVM: 0.925
Matriz de confusão:
[[117   7]
 [  5  31]]
Relatório de classificação:
              precision    recall  f1-score   support

        -1.0       0.96      0.94      0.95       124
         1.0       0.82      0.86      0.84        36

    accuracy                           0.93       160
   macro avg       0.89      0.90      0.89       160
weighted avg       0.93      0.93      0.93       160



In [37]:
#df_dados = pd.read_csv('df_bsi_sem_ativo.csv', sep=',')

In [38]:
"""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

# Load the dataset (exemplo com dados fictícios)
# df_dados = pd.read_csv('df_bsi_TR.csv', sep=',')

# Dados fictícios para exemplo
np.random.seed(0)
X = np.random.rand(100, 1) * 10
y = (np.sin(X).ravel() + np.random.randn(100) * 0.5) * 2

# Reduzir o tamanho do dataset para visualização rápida
# X = df_dados.drop(columns=['tempo_relativo']).to_numpy()
# y = df_dados['tempo_relativo'].to_numpy()

# Dividir em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Define SVR models with different kernels
svr_rbf = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)
svr_lin = SVR(kernel="linear", C=100, gamma="auto")
svr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)

svrs = [svr_rbf, svr_lin, svr_poly]
kernel_label = ["RBF", "Linear", "Polynomial"]
model_color = ["m", "c", "g"]

# Plot the results
fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(15, 5), sharey=True)
for ix, svr in enumerate(svrs):
    svr.fit(X_train, y_train)
    y_pred = svr.predict(X_test)
    
    axes[ix].scatter(X_test, y_test, color='k', s=20, label="Data")
    axes[ix].scatter(X_test, y_pred, color=model_color[ix], s=50, label="{} model".format(kernel_label[ix]), alpha=0.6)
    
    axes[ix].legend(loc="upper center", bbox_to_anchor=(0.5, 1.1), ncol=1, fancybox=True, shadow=True)
    axes[ix].set_title("{} SVR".format(kernel_label[ix]))

fig.text(0.5, 0.04, "Feature 1", ha="center", va="center")
fig.text(0.1, 0.5, "tempo_relativo", ha="center", va="center", rotation="vertical")
fig.suptitle("Support Vector Regression", fontsize=14)
plt.tight_layout()
plt.show()
"""

'import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.svm import SVR\nfrom sklearn.model_selection import train_test_split\n\n# Load the dataset (exemplo com dados fictícios)\n# df_dados = pd.read_csv(\'df_bsi_TR.csv\', sep=\',\')\n\n# Dados fictícios para exemplo\nnp.random.seed(0)\nX = np.random.rand(100, 1) * 10\ny = (np.sin(X).ravel() + np.random.randn(100) * 0.5) * 2\n\n# Reduzir o tamanho do dataset para visualização rápida\n# X = df_dados.drop(columns=[\'tempo_relativo\']).to_numpy()\n# y = df_dados[\'tempo_relativo\'].to_numpy()\n\n# Dividir em conjunto de treino e teste\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)\n\n# Define SVR models with different kernels\nsvr_rbf = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)\nsvr_lin = SVR(kernel="linear", C=100, gamma="auto")\nsvr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)\n\nsvrs = [svr_rbf, svr_lin, svr_poly]\nkernel_

In [39]:
"""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVR

# Load the dataset
df_dados = pd.read_csv('df_bsi_TR.csv', sep=',')

# Separate features (X) and target (y)
X = df_dados.drop(columns=['tempo_relativo']).to_numpy()
y = df_dados['tempo_relativo'].to_numpy()

# Define SVR models with different kernels
svr_rbf = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)
svr_lin = SVR(kernel="linear", C=100, gamma="auto")
svr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)

# Fit the models
svrs = [svr_rbf, svr_lin, svr_poly]
kernel_label = ["RBF", "Linear", "Polynomial"]
model_color = ["m", "c", "g"]

# Plot the results
fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(15, 10), sharey=True)
for ix, svr in enumerate(svrs):
    svr.fit(X, y)
    y_pred = svr.predict(X)
    
    axes[ix].scatter(X[:, 0], y, color='k', s=20, label="Data")
    axes[ix].scatter(X[:, 0], y_pred, color=model_color[ix], s=50, label="{} model".format(kernel_label[ix]), alpha=0.6)
    
    axes[ix].legend(loc="upper center", bbox_to_anchor=(0.5, 1.1), ncol=1, fancybox=True, shadow=True)
    axes[ix].set_title("{} SVR".format(kernel_label[ix]))

fig.text(0.5, 0.04, "Feature 1", ha="center", va="center")
fig.text(0.1, 0.2, "tempo_relativo", ha="center", va="center", rotation="vertical")
fig.suptitle("Support Vector Regression", fontsize=14)
plt.show()
"""

'import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.svm import SVR\n\n# Load the dataset\ndf_dados = pd.read_csv(\'df_bsi_TR.csv\', sep=\',\')\n\n# Separate features (X) and target (y)\nX = df_dados.drop(columns=[\'tempo_relativo\']).to_numpy()\ny = df_dados[\'tempo_relativo\'].to_numpy()\n\n# Define SVR models with different kernels\nsvr_rbf = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)\nsvr_lin = SVR(kernel="linear", C=100, gamma="auto")\nsvr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)\n\n# Fit the models\nsvrs = [svr_rbf, svr_lin, svr_poly]\nkernel_label = ["RBF", "Linear", "Polynomial"]\nmodel_color = ["m", "c", "g"]\n\n# Plot the results\nfig, axes = plt.subplots(nrows=1, ncols=3, figsize=(15, 10), sharey=True)\nfor ix, svr in enumerate(svrs):\n    svr.fit(X, y)\n    y_pred = svr.predict(X)\n    \n    axes[ix].scatter(X[:, 0], y, color=\'k\', s=20, label="Data")\n    axes[ix].scatter(X[:, 0], y_pred, color

In [40]:
"""import matplotlib.pyplot as plt
import numpy as np

from sklearn.svm import SVR

X = np.sort(5 * np.random.rand(40, 1), axis=0)
y = np.sin(X).ravel()

# add noise to targets
y[::5] += 3 * (0.5 - np.random.rand(8))

svr_rbf = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)
svr_lin = SVR(kernel="linear", C=100, gamma="auto")
svr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)

lw = 2

svrs = [svr_rbf, svr_lin, svr_poly]
kernel_label = ["RBF", "Linear", "Polynomial"]
model_color = ["m", "c", "g"]

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(15, 10), sharey=True)
for ix, svr in enumerate(svrs):
    axes[ix].plot(
        X,
        svr.fit(X, y).predict(X),
        color=model_color[ix],
        lw=lw,
        label="{} model".format(kernel_label[ix]),
    )
    axes[ix].scatter(
        X[svr.support_],
        y[svr.support_],
        facecolor="none",
        edgecolor=model_color[ix],
        s=50,
        label="{} support vectors".format(kernel_label[ix]),
    )
    axes[ix].scatter(
        X[np.setdiff1d(np.arange(len(X)), svr.support_)],
        y[np.setdiff1d(np.arange(len(X)), svr.support_)],
        facecolor="none",
        edgecolor="k",
        s=50,
        label="other training data",
    )
    axes[ix].legend(
        loc="upper center",
        bbox_to_anchor=(0.5, 1.1),
        ncol=1,
        fancybox=True,
        shadow=True,
    )

fig.text(0.5, 0.04, "data", ha="center", va="center")
fig.text(0.06, 0.5, "target", ha="center", va="center", rotation="vertical")
fig.suptitle("Support Vector Regression", fontsize=14)
plt.show()"""

'import matplotlib.pyplot as plt\nimport numpy as np\n\nfrom sklearn.svm import SVR\n\nX = np.sort(5 * np.random.rand(40, 1), axis=0)\ny = np.sin(X).ravel()\n\n# add noise to targets\ny[::5] += 3 * (0.5 - np.random.rand(8))\n\nsvr_rbf = SVR(kernel="rbf", C=100, gamma=0.1, epsilon=0.1)\nsvr_lin = SVR(kernel="linear", C=100, gamma="auto")\nsvr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)\n\nlw = 2\n\nsvrs = [svr_rbf, svr_lin, svr_poly]\nkernel_label = ["RBF", "Linear", "Polynomial"]\nmodel_color = ["m", "c", "g"]\n\nfig, axes = plt.subplots(nrows=1, ncols=3, figsize=(15, 10), sharey=True)\nfor ix, svr in enumerate(svrs):\n    axes[ix].plot(\n        X,\n        svr.fit(X, y).predict(X),\n        color=model_color[ix],\n        lw=lw,\n        label="{} model".format(kernel_label[ix]),\n    )\n    axes[ix].scatter(\n        X[svr.support_],\n        y[svr.support_],\n        facecolor="none",\n        edgecolor=model_color[ix],\n        s=50,\n        lab

Separando dados de treinamento e teste

Divisão dos dados Treino e testes